name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Exec deeploy.sh script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            su louisdelatech
            cd /opt/LouisDeLaTech
            git pull
            exit
            sudo systemctl restart louisdelatech
